name: Deploy to Apex Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /root/Apex_Server_Bridge
          bash deploy.sh
